sudo: required
language: go
env:
  global:
  - DOCKER_VERSION=1.10.1-0~trusty
  - DOCKER_COMPOSE_VERSION=1.6.0
services:
- docker
before_install:
- sudo apt-get -o Dpkg::Options::="--force-confnew" install -y docker-engine=${DOCKER_VERSION}
- wget https://storage.googleapis.com/kubernetes-release/release/v1.2.0/bin/linux/amd64/kubectl
- chmod +x kubectl && sudo mv kubectl /usr/local/bin/kubectl
- curl -L https://github.com/docker/compose/releases/download/1.6.2/docker-compose-`uname
  -s`-`uname -m` > docker-compose
- sudo mv docker-compose /usr/local/bin/docker-compose && sudo chmod +x /usr/local/bin/docker-compose
- docker-compose up -d
- "./broadway-setup-kubernetes-namespace.sh"
install: true
script:
- docker-compose run test go test $(go list ./... | grep -v 'vendor/')
deploy:
  provider: script
  script: "./deploy.sh"
  on:
    branch: master
notifications:
  slack:
    secure: KUc8ZrE3lCM+ZiUrosvq0kfX9HwYUVQBEe7N4rlv7MsgfDhrHjLsRZVJIBzAJ72XAnQwVqkPVSh/7UVhyO1BDCz/Bf0yirZHTaUlcnFT1Gp/aPoOeAQiikNnOTCuwf2ssTf9FePe+/aHm5FK8ZiAg4ZPz4EeIf9tKZf37VLOlsn8VCb+sqCY6knv+K8lbWtmtzgbJdzS2+rOYDGyRzW+4Hl05EXsXd5BXEhS/mCXpc640wbde1Q0dFgFfBnSAJrJAaOjuiXPZnZFOpYQP9dFc+Xf36hpCZGW89NMDyq++ZgYT2+6Gf6okQXhfaGWiEHIlnpUdXtogQKNPn94GADveCV1Zdtgpw2xppBFsz3CfY2CTv81ghHgZ/UNZsBL843Ue2E/o3T1xKhTaGz3myvbxVhcXy/p16vTGaPMqUfxcbEwh2ilA0Cy+t7/YjaCLfqlA+m6uybdYPnxLZUV93Xpbu4odDDQQVKMAWJwoVILMUnXGZMjcqJ3RXvFIErzyWTJcyPdjhOTSLgLigC4r3jSgySy6ey/uBOmrKSH3ew5Iu6Bk5Ut4jruGgtgx4LNkOelZtj40FxEscbbLAaZHX7yHt9i179jSp3pvKO7lKbz+PZCVXGVDE5dm30lM/3VEEScEszVQlLe8k7lKEKlgaQhBdxsA6cI4F6tjYNkpYai7VI=
